ARG BASE_TAG=latest
FROM rocm/dev-ubuntu-24.04:${BASE_TAG}

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y locales git cmake wget curl gnupg2 lsb-release python3-numpy python3-setuptools python3-wheel && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8


RUN apt update && apt install -y build-essential ca-certificates python3-dev \
                    migraphx migraphx-dev half && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --recursive https://github.com/microsoft/onnxruntime /tmp/onnxruntime && \
    cd /tmp/onnxruntime && \
    ./build.sh --config Release --build_shared_lib --parallel \
      --use_migraphx --migraphx_home /opt/rocm \
      --update --build --skip_tests --allow_running_as_root && \
    cd build/Linux/Release && \
    cmake --install . --prefix /opt/onnxruntime-migraphx && \
    echo /opt/onnxruntime-migraphx/lib > /etc/ld.so.conf.d/onnxruntime.conf && \
    ldconfig && \
    rm -rf /tmp/onnxruntime

RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    sed -i -e 's/ubuntu .* main/ubuntu noble main/g' /etc/apt/sources.list.d/ros2.list && \
    apt update && \
    apt install -y ros-dev-tools \
                    ros-jazzy-cv-bridge \
                    ros-jazzy-generate-parameter-library \
                    ros-jazzy-parameter-traits \
                    ros-jazzy-ros-base \
                    ros-jazzy-rqt-image-view \
                    ros-jazzy-usb-cam \
                    ros-jazzy-vision-msgs && \
    apt -y clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY ./ros_entrypoint.sh /ros_entrypoint.sh
RUN echo "source /ros_entrypoint.sh" >> /root/.bashrc
