version: '3.4'
services:
    yolox_ros:
        container_name: yolox_tensorrt
        build:
            context: .
            args:
                - TENSORRT_VERSION=8.6
                - CUDNN_VERSION=8.8
                - PYTHON_VERSION=3.10
        network_mode: host
        runtime: nvidia
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - $HOME/ros2_ws:/root/ros2_ws
            - /tmp/.X11-unix:/tmp/.X11-unix
        devices:
            - "/dev/video0:/dev/video0"
        working_dir: /root/ros2_ws
        tty: true
        command: bash

