ARG BASE_TAG=11.7.1-cudnn8-devel-ubuntu22.04
FROM nvcr.io/nvidia/cuda:${BASE_TAG}
ENV	 DEBIAN_FRONTEND=noninteractive

ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
RUN apt update && \
    apt install -y python3-dev python3-pip \
                   ca-certificates g++ gcc make git aria2 && \
    apt -y clean && \
    rm -rf /var/lib/apt/lists/* && \
    aria2c -q -d /tmp -o cmake-3.21.0-linux-x86_64.tar.gz https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.tar.gz && \
    tar -zxf /tmp/cmake-3.21.0-linux-x86_64.tar.gz --strip=1 -C /usr
RUN python3 -m pip install -U pip && \
    python3 -m pip install -U numpy setuptools wheel && \
    python3 -m pip cache purge

WORKDIR /workdir
RUN git clone --depth 1 --recursive https://github.com/microsoft/onnxruntime -b v1.12.1 && \
    cd onnxruntime && \
    ./build.sh --cudnn_home /usr/lib/x86_64-linux-gnu/ \
               --cuda_home /usr/local/cuda \
               --use_cuda \
               --config RelWithDebInfo \
               --build_shared_lib \
               --skip_tests && \
    cd build/Linux/RelWithDebInfo && \
    make install && \
    rm -r /workdir/onnxruntime

# Install ROS2
RUN apt update && apt install locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    apt -y clean && \
    rm -rf /var/lib/apt/lists/*
ENV LANG=en_US.UTF-8

RUN apt update && \
    apt install -y git wget curl gnupg2 lsb-release && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    sed -i -e 's/ubuntu .* main/ubuntu jammy main/g' /etc/apt/sources.list.d/ros2.list && \
    apt update && \
    apt install -y ros-dev-tools \
                    ros-humble-cv-bridge \
                    ros-humble-generate-parameter-library \
                    ros-humble-parameter-traits \
                    ros-humble-ros-base \
                    ros-humble-rqt-image-view \
                    ros-humble-v4l2-camera && \
    apt -y clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install -U pip && \
    pip install catkin_pkg && \
    pip install empy && \
    pip install lark && \
    python3 -m pip cache purge


COPY ./ros_entrypoint.sh /ros_entrypoint.sh
RUN echo "source /ros_entrypoint.sh" >> /root/.bashrc
# ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]
