FROM openvino/ubuntu22_dev:2023.0.1

ENV DEBIAN_FRONTEND=noninteractive

USER root

# Install ROS2
RUN apt update && \
    apt install -y git wget curl gnupg2 lsb-release && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    sed -i -e 's/ubuntu .* main/ubuntu jammy main/g' /etc/apt/sources.list.d/ros2.list && \
    apt update && \
    apt install -y ros-humble-ros-base \
                   ros-humble-v4l2-camera \
                   ros-humble-cv-bridge \
                   ros-humble-rqt-image-view \
                   ros-humble-parameter-traits \
                   ros-dev-tools && \
    apt -y clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
COPY ./ros_entrypoint.sh /ros_entrypoint.sh
RUN echo "source /ros_entrypoint.sh" >> /root/.bashrc
# RUN echo "source /opt/intel/openvino/bin/setupvars.sh " >> /root/.bashrc
CMD ["bash"]